# Generated by Django 2.0.5 on 2018-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('is_sell', models.BooleanField(default=True)),
                ('memory_rom', models.IntegerField()),
                ('memory_ram', models.IntegerField()),
            ],
        ),
    ]
