# Generated by Django 2.0.5 on 2018-08-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='memory_ram',
            new_name='ram',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='memory_rom',
            new_name='rom',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='is_sell',
        ),
        migrations.AddField(
            model_name='phone',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
