# Generated by Django 2.0.5 on 2018-06-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20180627_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
